baseURL = "https://takashi-noneq.com/"
theme = "PaperMod"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Takashi Goto"

    [[languages.en.menu.main]]
      name = "CV"
      url = "/en/cv/"
      weight = 10

    [[languages.en.menu.main]]
      name = "Research"
      url = "/en/Research/"
      weight = 20

    [[languages.en.menu.main]]
      name = "Presentations"
      url = "/en/Presentations/"
      weight = 20

  [languages.ja]
    languageName = "日本語"
    weight = 2
    title = "後藤 崇志"