baseURL = "https://takashi-noneq.com/"
theme = "PaperMod"

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    label = "English"
    weight = 1
    title = "Takashi Goto"

    [[languages.en.menu.main]]
      name = "CV"
      url = "/en/cv/"
      weight = 10

    [[languages.en.menu.main]]
      name = "Research"
      url = "/en/research/"
      weight = 11

    [[languages.en.menu.main]]
      name = "Presentations"
      url = "/en/presentations/"
      weight = 12

    [[languages.en.menu.main]]
      name = "Notebook"
      url = "/en/notebook/"
      weight = 20

  [languages.ja]
    label = "日本語"
    weight = 2
    title = "後藤 崇志"

    [[languages.ja.menu.main]]
      name = "略歴・プロフィール"
      url = "/ja/cv/"
      weight = 10

    [[languages.ja.menu.main]]
      name = "研究内容"
      url = "/ja/research/"
      weight = 11

    [[languages.ja.menu.main]]
      name = "発表・学術講演"
      url = "/ja/presentations/"
      weight = 12

    [[languages.ja.menu.main]]
      name = "備忘録"
      url = "/ja/notebook/"
      weight = 20

[params]
  images = ["/images/takashigoto_mayfes_m_sb50pix-binthresh215.jpg"]
  
  [params.assets]
    favicon = "/images/favicon.ico"
    favicon16x16 = "/images/favicon-16x16.png"
    favicon32x32 = "/images/favicon-32x32.png"
    apple_touch_icon = "/images/apple-touch-icon.png"